# 

---

- hosts: all

  become: true

  tasks:

    - name: Install Packages

      apt: name={{ item }} update_cache=yes state=latest

      loop: [ 'nginx', 'vim' ]

      tags: [ 'setup' ]

    - name: Install aptitude

      apt:

        name: aptitude

        state: latest

        update_cache: true


    - name: Copy index page

      copy:

        src: index.html

        dest: /var/www/html/index.html

        owner: www-data

        group: www-data

        mode: '0644'